Todo app
mntedev/React-Todo-App pull request #3
Opened 2022-07-08 20:32 UTC by worashf

I have completed the following tasks.

    implemented add todo, delete todo, update todo and render todos using class components.
    implemented add todo, delete todo, update todo and render todos using functional components.
    used useState and UseEffect hooks
    added routing using react-router dom
    added styling for react components
    added icon to react components

2022-07-08 20:51 UTC, waqaskanju requested changes

2022-07-08 20:51 UTC, waqaskanju commented on README.md
> +> This project is created to demonistrate how to create react application. To learn react class compoent, events, fucntional componets and hooks.
change spelling

2022-07-08 20:51 UTC, waqaskanju commented on README.md
> +> This project is created to demonistrate how to create react application. To learn react class compoent, events, fucntional componets and hooks.
Change spelling of component and functional

2022-07-08 20:51 UTC, waqaskanju commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Mit.md file not found

2022-07-08 20:51 UTC, waqaskanju commented on public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
Remove files which you are not using.
![image](https://user-images.githubusercontent.com/13853450/178067345-c857b2dc-77d2-4306-9bbb-24842adaaa63.png)

2022-07-08 20:51 UTC, waqaskanju commented on src/index.js
> +import Navbar from './functionBased/components/Navbar';
Correct the nav bar it should be only visible in Mobile view not in desktop.
![image](https://user-images.githubusercontent.com/13853450/178067650-5b7f2c42-d01d-407e-90a3-c3b67020426f.png)

2022-07-08 20:51 UTC, waqaskanju commented on src/index.js
> +        <Route path="/about" element={<About />} />
You class base show errors.
![image](https://user-images.githubusercontent.com/13853450/178068103-35e218a4-3846-42a8-a4ea-514f4c015db8.png)

2022-07-08 20:51 UTC, waqaskanju commented on src/classBased/components/TodoList.js
> +            deleteItem={this.props.deleteItem}
The delete option in class base is not working.
![image](https://user-images.githubusercontent.com/13853450/178068246-c1cae991-e3c1-49e8-964b-70a963d3d573.png)

2022-07-08 20:51 UTC, waqaskanju commented on src/classBased/components/TodoItem.module.css
> +}
The rest of application is working great.

2022-07-08 21:21 UTC, worashf commented
the menu is shown on both mobile and desktop devices, and can you give me a suggestion on how to correct the license.

2022-07-08 21:51 UTC, waqaskanju approved these changes

2022-07-08 21:52 UTC, merged

2022-07-08 21:52 UTC, waqaskanju commented
You code is working great

2022-09-12 21:21 UTC, waqaskanju commented
> I have completed the following tasks.
> 
> ```
> implemented add todo, delete todo, update todo and render todos using class components.
> implemented add todo, delete todo, update todo and render todos using functional components.
> used useState and UseEffect hooks
> added routing using react-router dom
> added styling for react components
> added icon to react components
> ```

Good Work Worish!
Your readme File is good
There are no linter errors
Your project is runnable.

There are some suggestion listed below.